name: celestialtype
services:
- name: api
  github:
    branch: test
    deploy_on_push: true
    repo: Amrot97/celestialtype
  build_command: pip install -r requirements.txt
  run_command: gunicorn backend.wsgi:application
  envs:
  - key: DJANGO_SETTINGS_MODULE
    value: backend.production_settings
  - key: DJANGO_SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ALLOWED_HOSTS
    value: ".ondigitalocean.app"
  - key: CORS_ALLOWED_ORIGINS
    value: "https://*.ondigitalocean.app"
  http_port: 8000
  instance_count: 1
  instance_size_slug: basic-xxs 