# Generated by Django 5.0.6 on 2024-09-15 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dom", models.IntegerField()),
            ],
            options={
                "db_table": "dom",
            },
        ),
        migrations.CreateModel(
            name="Planeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("planety", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "planet",
            },
        ),
        migrations.CreateModel(
            name="Znak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("znaki", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "znak",
            },
        ),
        migrations.CreateModel(
            name="Aspekt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subheader", models.CharField(blank=True, max_length=255, null=True)),
                ("key_traits", models.TextField(blank=True, null=True)),
                ("opis", models.TextField(blank=True, null=True)),
                (
                    "dom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="natal_chart.dom",
                    ),
                ),
                (
                    "planeta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="natal_chart.planeta",
                    ),
                ),
                (
                    "znak",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="natal_chart.znak",
                    ),
                ),
            ],
            options={
                "db_table": "Aspekty",
            },
        ),
    ]
